# Generated by Django 3.0.5 on 2020-04-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='static/market/img')),
                ('like_number', models.IntegerField()),
                ('buy_number', models.IntegerField()),
                ('qte_stock', models.IntegerField()),
                ('base_price', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('categorie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.Categorie')),
            ],
        ),
    ]
