# Generated by Django 3.0.5 on 2020-04-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200412_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='poster',
            field=models.BooleanField(default=False),
        ),
    ]
