# Generated by Django 3.0.5 on 2020-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_produit_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ManyToManyField(to='market.Categorie'),
        ),
    ]
